[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_work = "BqLqm3KGicFQfr9tGeuXGbHrRZV95voXEECHphxCxicW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/solana-work/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
