[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_work = "Bv33hU1UuzxBbtB3EXST7d39hFQfBA3aY6NYqYLMtEv1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
