[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_work_practice = "6gP86XwGHXuRU1yNdBWnwd9unPNuQjy3Sr7T3oe7aQbW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/solana-work-practice/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
